name: Publish 1.17 To GitHub Repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Inject Commit Revision
        run: "echo \"-${GITHUB_SHA::8}\" >> git_reference_id.txt"

      - name: Generate 1.17 data
        run: sudo gradle clean cleanAllMinecraft generateData_1.17

      - name: Push 1.17 Data
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "ArticData/1.17/"
          user-email: "articdata@bot.io"
          destination-github-username: "Articdive"
          destination-repository-name: "ArticData"
          target-branch: "1.17"