name: Publish To GitHub Repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate data for all versions
      run: ./gradlew generateAllData -Peula=true

    - name: Push 1.16.3 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.16.3/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.16.3"

    - name: Push 1.16.4 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.16.4/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.16.4"

    - name: Push 1.16.5 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.16.5/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.16.5"

    - name: Push 1.17 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.17/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.17"

    - name: Push 1.17.1 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.17.1/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.17.1"

    - name: Push 1.18 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.18/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.18"