name: Publish 1.18 To GitHub Repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 17
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate 1.18 data
      run: gradle clean cleanAllMinecraft generateData_1.18

    - name: Push 1.18 Data
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "ArticData/1.18/"
        user-email: "articdata@bot.io"
        destination-github-username: "Articdive"
        destination-repository-name: "ArticData"
        target-branch: "1.18"